### ISSUE TITLE
Only first and second workspaces are saved after reload

### ISSUE THREAD

**Issue by GoshaEgorian** [material-shell/material-shell#358]
**Describe the bug**
Consider you set up a few workspaces (3 and more) and make all app in there "fully persistent". Then you reload you pc. Only first 2 of workspaces will be saved and all others will be cleared. I tried it to reproduce and it happens in one of three cases approximately but it's stable bug. 

**Expected behavior**
All workspaces should be saved between reloads.

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [ ] Wayland
- GNOME Shell version: 3.36
- Distro: Ubuntu 20.04
- Steps to reproduce, if applicable:
1. Set up up to 3 workspaces or more
2. Make all apps "fully consistent" (maybe it's not necessary)
3. Reload pc
4. If all workspaces exist repeat 3
5. If it doesn't it's bug

**Current commit**
`ec73be7`

**Comment by aaronjanse** [comment]
Related to #349

**Comment by lfom** [comment]
It should be fixed after https://github.com/material-shell/material-shell/commit/b8bd14804b5f737492c15cbbc8f980afded83f64

**Comment by GoshaEgorian** [comment]
Behavior changed but it's still reproducible (commit `21b48f8`). This time only one workspace disappeared.
[material-shell.log](https://github.com/material-shell/material-shell/files/5333945/material-shell.log)

**Comment by PapyElGringo** [comment]
Can you reproduce with https://github.com/material-shell/material-shell/commit/fc27489a1ec503a4a5c7cb2f4e1eefa84a7ea2f1 (Before I remove the logs :smile: )

**Comment by GoshaEgorian** [comment]
Sure, here it is
[material-shell.log](https://github.com/material-shell/material-shell/files/5334094/material-shell.log)

Also I attach a screenshot so you can see only 2 workspaces was actually restored.

![Screenshot from 2020-10-06 16-24-51](https://user-images.githubusercontent.com/8870929/95207481-99465180-07f0-11eb-9fee-bef8d457f6f1.png)

**Comment by PapyElGringo** [comment]
something else seem to manipualte the workspaces try dissable other extension

**Comment by GoshaEgorian** [comment]
I turned off every other extension already (this part can be in the log beginning). Last two reboots are clear (MS is the only turned on extension).

**Comment by GoshaEgorian** [comment]
I looked at the log file and found a few strings which look a little bit strange for me:
```log
Oct 06 16:22:15 ocean gnome-shell[2399]: JS WARNING: [/home/george-egorian/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/layout/msWorkspace/msWindow.js 120]: reference to undefined property "msWindowDragged"
Oct 06 16:22:15 ocean gnome-shell[2399]: Could not create transient scope for PID 3129: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 3129 does not exist.
Oct 06 16:22:15 ocean gnome-shell[2399]: [DEBUG], Workspace 4 was removed
Oct 06 16:22:15 ocean gnome-shell[2399]: [DEBUG], stateChanged from removeMsWorkspaceAtIndex
Oct 06 16:22:15 ocean gnome-shell[2399]: [DEBUG], Inside stateChanged
Oct 06 16:22:15 ocean gnome-shell[2399]: [DEBUG], Workspace 3 was removed
Oct 06 16:22:15 ocean gnome-shell[2399]: [DEBUG], stateChanged from removeMsWorkspaceAtIndex
Oct 06 16:22:15 ocean gnome-shell[2399]: [DEBUG], Workspace 2 was removed
Oct 06 16:22:15 ocean gnome-shell[2399]: [DEBUG], stateChanged from removeMsWorkspaceAtIndex
Oct 06 16:22:15 ocean gnome-shell[2399]: [DEBUG], Workspace 2 was added
Oct 06 16:22:15 ocean gnome-shell[2399]: [DEBUG], Setup a new Workspace
Oct 06 16:22:15 ocean gnome-shell[2399]: [DEBUG], Create new MS Workspace: Restoring previous state? NO
```
Three workspaces was removed and only one was added. That's looking related to my actually visible workspace's changes (was 4 and become 2 after reload). This remark can be wrong because I just glanced at the logs.

**Comment by PapyElGringo** [comment]
Yeah if you read all the logs you will sse that we properly restored the 4 workspacesss but then something destroy the 3 restored workspace to then readd an empty one. It's wierd do you have a number of fixed workspace in Gnome tweak?

**Comment by real-or-random** [comment]
I can reproduce this with 21b48f8c49efe4623391d750bafbcbe95b29cd22, 3.38, Arch Linux. 

But I don't see any `[DEBUG]` messages in the log. Is there some debug option that I need to enable?

**Comment by NastuzziSamy** [comment]
We maybe have the cause: auto-move extension conflicts
The current fix is to disable the auto-move extension.

If someone wants to work on that: https://github.com/material-shell/material-shell/issues/410

**Comment by GoshaEgorian** [comment]
I don't have 'auto-move' extension installed and never use it.
There wasn't any extensions enabled when I reproduce this bug few last times.
