### ISSUE TITLE
Material-shell is not usable after waking up (Gnome 3.38)

### ISSUE THREAD

**Issue by yannhodiesne** [material-shell/material-shell#372]
**Describe the bug**
My laptop suspends itself after 10 minutes of inactivity for battery life reasons, but since I installed Gnome 3.38 material-shell is not usable after waking it up :
 - the top bar showing open windows shifts itself to the left
 - as I navigate between workspaces and apps, the top bar and current apps windows does not appear on the screen (I only see my background)
 - if I navigate enough between workspaces and apps, my system becomes unreasonably slow

**Expected behavior**
I don't think I have to describe anything there

**Screenshots**
It is hard to get a good screenshot as it seems to fix the problem for a small amount of time when the screen shot is taken, but I got one there : [Top bar and applications windows missing](https://i.imgur.com/atV9cVW.png)

**To Reproduce**
- Occurs on:
  - [ ] X.Org
  - [x] Wayland
- GNOME Shell version: 3.38 (upgraded this morning)
- Distro: Archlinux (all packages updated today)
- Steps to reproduce, if applicable:
1. Boot the system, login and use material-shell without any problem
2. Put the system to sleep (suspend mode)
3. Wake it up, the top bar is already shifted to the left
4. Try to navigate between workspaces and apps, the applications windows disappear

**Current commit**
Output from `git rev-parse --short HEAD`: `21b48f8`

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
oct. 06 12:05:16 notebork gnome-shell[1746]: Could not create transient scope for PID 3778: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 3778 does not exist.
oct. 06 12:05:16 notebork gnome-shell[1746]: Could not create transient scope for PID 3779: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 3779 does not exist.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor MsMain is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor PrimaryMonitorContainer is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor TranslationAnimator is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor ClutterActor is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor MsWorkspaceActor is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor ClutterActor is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor MsWindow is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor MsWindowContent is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor ClutterClone is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor topPanel is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor taskBar is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor StWidget is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor ClutterActor is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor MsMain is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor PrimaryMonitorContainer is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor TranslationAnimator is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor ClutterActor is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor MsWorkspaceActor is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor ClutterActor is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor MsWindow is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor MsWindowContent is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor ClutterClone is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor topPanel is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor taskBar is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor StWidget is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor ClutterActor is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor MsMain is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor PrimaryMonitorContainer is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor TranslationAnimator is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor ClutterActor is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor MsWorkspaceActor is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor ClutterActor is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor MsWindow is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor MsWindowContent is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor ClutterClone is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor topPanel is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor taskBar is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor StWidget is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor ClutterActor is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor MsMain is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor PrimaryMonitorContainer is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor TranslationAnimator is on because it needs an allocation.
oct. 06 12:05:17 notebork gnome-shell[1746]: Can't update stage views actor ClutterActor is on because it needs an allocation.
```

These last lines are repeated until I open a system menu (like the sound/network/user one on the bottom left), which seems to put Material-shell in a usable state again

**Comment by ackstorm23** [comment]
Same here, except on Xorg.   Running 3.38 as well.

**Comment by PapyElGringo** [comment]
Should be fixed now?

**Comment by ackstorm23** [comment]
I am still experiencing this, not sure about the original poster.

**Comment by PapyElGringo** [comment]
Did you pulled master recently? If it still have issue you could try to disable others extensions to see if there is an incompatibility

**Comment by ackstorm23** [comment]
I had pulled it from about 2 weeks ago after seeing another big for what appeared to be the same issue was marked fixed.

I've pulled it fresh and restarted.  so far, so good.
