### ISSUE TITLE
Touching the title bar with a touch screen makes it unusable, requiring a mouse to "unlock"

### ISSUE THREAD

**Issue by hashworks** [material-shell/material-shell#394]
**Describe the bug**
When one touches the title bar with a touch screen it becomes completely unresponsive. No further inputs from the touchscreen are possible. This state can only be departed by using a mouse. This happens because touching the title bar "moves" the window, but it is still locked in place by material shell. Using a mouse then enables the user to "move" the window a bit and click to release it, which results in it snapping back into place (since it is managed by material shell).

This is quite some issue, since it makes the whole device unusable when one only uses a touchscreen. One has to attach a mouse / mouse pad to the unresponsive tablet to make it usable again.

**Expected behavior**
Moving windows with the touchscreen should be a simple drag and drop, releasing the finger should release the movement state. An alternative would be to disable the trigger of movement when one touches the title bar.

**To Reproduce**
- Occurs on:
  - [ ] X.Org (Not tested)
  - [X] Wayland
- GNOME Shell version: 3.36
- Distro: Arch Linux
- Steps to reproduce, if applicable:
1. Run Material Shell on a device with a touchscreen
2. Touch the title bar of any window
3. Notice how the device is unresponsive
4. Use a mouse to make the touchscreen usable again

**Current commit**
Output from `git rev-parse --short HEAD`: `d7478d7`

**Comment by sebastian-xyz** [comment]
The issue seems to be related to #382.

**Comment by PapyElGringo** [comment]
Should be fixed

**Comment by ethan961** [comment]
I am experiencing this issue still on both the latest commit 56a7b591690cbd8621e003282b717f0c9a7a5fb0 and the versions provided by Fedora and the GNOME Extensions page (v10). 

Tested on Wayland and GNOME 3.38, Fedora 33. 

I don't experience issues regarding #382 or #452, only this issue when tapping a title bar.
