### ISSUE TITLE
Touch Screen Side App group bug

### ISSUE THREAD

**Issue by nibirrayy** [material-shell/material-shell#452]
I am currently using manjaro on a 2 in 1 laptop. When I use my touch screen to rearrange app groups on the side launcher it freezes the entire gnome shell sometimes even keyboard and pointer inputs. Most of the time it only freezes keyboard input.

The only way to get back is to logout of the gnome shell by logging off or by shutting it down. It is so bad that I have to take a screenshot of the bug using my phone
![Bug](https://user-images.githubusercontent.com/12048453/97786080-0a4e0e80-1bcf-11eb-8669-0fbe56950b14.jpg)

Take a look at the top left corner. My browser app group. It is frozen and is floating

**Comment by expeehaa** [comment]
Using a Surface Go with openSUSE Tumbleweed, gnome 3.36 and material-shell version 9, I can't reproduce that bug.

**Comment by jugendhacker** [comment]
I ran reproduce this on my Thinkpad X1 Yoga 2nd Gen with Arch Linux an GNOME 3.38, sometimes also the window titles freak out when I touch on them.

**Comment by nibirrayy** [comment]
Seems this bug is related to  #394

**Comment by jugendhacker** [comment]
Yeah seems like a duplicate of #382

**Comment by PapyElGringo** [comment]
Should be fixed

**Comment by jugendhacker** [comment]
Now when I touch on a workspace icon in the sidebar mouse and touch selection of windows & workspaces is completely until i reload/reboot @PapyElGringo

**Comment by PapyElGringo** [comment]
Could you elaborate please? Do you have any error in the logs?

**Comment by jugendhacker** [comment]
This is what gnome-shell logs into journalctl after triggering the bug
```
Nov 09 15:29:12 x1-yoga-arch gnome-shell[14008]: libinput error: event5  - Wacom Pen and multitouch sensor Finger: client bug: event processing lagging behind by 119ms, your system is too slow
Nov 09 15:29:12 x1-yoga-arch gnome-shell[14008]: Timelines with detached actors are not supported
Nov 09 15:29:12 x1-yoga-arch gnome-shell[14008]: Timelines with detached actors are not supported
Nov 09 15:29:12 x1-yoga-arch gnome-shell[14008]: Timelines with detached actors are not supported
Nov 09 15:29:16 x1-yoga-arch gnome-shell[14008]: clutter_event_get_button: assertion 'event->type == CLUTTER_BUTTON_PRESS || event->type == CLUTTER_BUTTON_RELEASE || event->type == CLUTTER_PAD_BUTTON_PRESS || event->type == CLUTTER_PAD_BUTTON_RELEASE' failed
Nov 09 15:29:16 x1-yoga-arch gnome-shell[14008]: [DEBUG], stateChanged from switch-workspace
Nov 09 15:29:16 x1-yoga-arch gnome-shell[14008]: [DEBUG], _checkWorkspaces
Nov 09 15:29:16 x1-yoga-arch gnome-shell[14008]: [DEBUG], Inside stateChanged
Nov 09 15:29:16 x1-yoga-arch gnome-shell[14008]: [DEBUG], saveCurrentState
Nov 09 15:29:16 x1-yoga-arch gnome-shell[14008]: [DEBUG], _checkWorkspaces
Nov 09 15:29:16 x1-yoga-arch gnome-shell[14008]: Could not create transient scope for PID 15655: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 15655 does not exist.
Nov 09 15:29:16 x1-yoga-arch gnome-shell[14008]: Timelines with detached actors are not supported
Nov 09 15:29:23 x1-yoga-arch gnome-shell[14008]: [DEBUG], stateChanged from switch-workspace
Nov 09 15:29:23 x1-yoga-arch gnome-shell[14008]: [DEBUG], _checkWorkspaces
Nov 09 15:29:23 x1-yoga-arch gnome-shell[14008]: [DEBUG], Inside stateChanged
Nov 09 15:29:23 x1-yoga-arch gnome-shell[14008]: [DEBUG], saveCurrentState
Nov 09 15:29:23 x1-yoga-arch gnome-shell[14008]: [DEBUG], _checkWorkspaces
Nov 09 15:29:24 x1-yoga-arch gnome-shell[14008]: libinput error: event17 - SynPS/2 Synaptics TouchPad: client bug: event processing lagging behind by 17ms, your system is too slow
```

**Comment by PapyElGringo** [comment]
I guess it's this but it's wierd
```
Nov 09 15:29:16 x1-yoga-arch gnome-shell[14008]: clutter_event_get_button: assertion 'event->type == CLUTTER_BUTTON_PRESS || event->type == CLUTTER_BUTTON_RELEASE || event->type == CLUTTER_PAD_BUTTON_PRESS || event->type == CLUTTER_PAD_BUTTON_RELEASE' failed
```

**Comment by PapyElGringo** [comment]
Could I get the logs before / during / after the touch on the workspace icon?

**Comment by jugendhacker** [comment]
How long before?

**Comment by PapyElGringo** [comment]
Just before

**Comment by PapyElGringo** [comment]
I updated master with new fixes is that good now?

**Comment by jugendhacker** [comment]
Now I can't trigger the bug anymore, but I also can't touch on
workspaces / windows anymore to switch to them... I could just reorder
them by drag'n'drop with touch.

Clicking on windows / workspaces still works normally.

**Comment by PapyElGringo** [comment]
Could you try last commit?

**Comment by jugendhacker** [comment]
Works now, thanks

**Comment by PapyElGringo** [comment]
Perfectly? You can now trigger context menu with long press

**Comment by nibirrayy** [comment]
@PapyElGringo the problem still persists and there is new issue opened  #471 Which seems the same as this one

**Comment by PapyElGringo** [comment]
@nibirrayy Even after updating to the last master commit and restarted your computer it's still break ????

**Comment by nibirrayy** [comment]
I restarted Gnome Shell and even logged off and yes it still breaks and sometimes it even freezes keyboard input

**Comment by hashworks** [comment]
Just to chime in, I'm at the latest master and it happens quite often (to the point where I just disable the extension). Funny thing is, this didn't happen to me before fcce4eb I think

**Comment by hashworks** [comment]
@PapyElGringo fixed for me with 87a255d.

@nibirrayy Could you try out the latest commit to confirm this?

**Comment by PapyElGringo** [comment]
You could you guys post some logs on pastbin so I can check?

**Comment by hashworks** [comment]
In [this X11 log session](https://fb.hash.works/9jPb8L) one single workspace (1) "froze" and I wasn't able to select it again. I could select workspace 0 and 2 though.

**Comment by jugendhacker** [comment]
> Perfectly? You can now trigger context menu with long press

Yeah works fine on my Thinkpad X1 Yoga 2nd gen with Arch Linux and Wayland

**Comment by hashworks** [comment]
Happened again [in this X11 session](https://fb.hash.works/WFgkyn). To me it seems like Gnome is "locked" in the reorder / movement operation since while I can select other workspaces I can't reorder them anymore. Also, as @nibirrayy said, keyboard freeze etc.

**Comment by PapyElGringo** [comment]
@hashworks I pushed some cleaning to prevent some error I guess but I'm not sure it was causing the bug could you pull and try again + new log? Also does pressing escape help to unstuck?

**Comment by nibirrayy** [comment]
@PapyElGringo I tired the new commit 1bfc57f80ef2deb447753d8ac29f89f724d34d4 still the same issue that I shared on my screenshot earlier and I can share my logs as the keyboard input freezes and the only way is to log out so the logs are getting cleared

**Comment by hashworks** [comment]
Why are your journalctl Logs cleared when you log out?

**Comment by hashworks** [comment]
@PapyElGringo [Happened](https://fb.hash.works/Utu1UwFV) in 1bfc57f on X11

**Comment by nibirrayy** [comment]
Here are my logs after logging in [log](https://termbin.com/8g4k)
look at the log beginning time @hashworks it cleared it and it started when i just logged in.

**Comment by PapyElGringo** [comment]
@nibirrayy I'm sorry but you are not using current Master commit

**Comment by hashworks** [comment]
> @nibirrayy I'm sorry but you are not using current Master commit

As he said, his system removes all logs after he logs out. The logs he posted are from 2020-10-17.

**Comment by PapyElGringo** [comment]
Ah indeed ^^ @hashworks your logs are like a warzone I don't understand why everything start to break

**Comment by nibirrayy** [comment]
@hashworks my bad I am working on my data science project and didn't have much sleep so i read the date wrong. I installed stacer and didn't set it up correctly. It was messing with my logs

**Comment by hashworks** [comment]
@PapyElGringo Shooting out logs at 833 LPM!

[Another one in X11](https://4D5avy), this time I disabled all other extensions (Draw on Your Screen, GSConnect, OpenWeather) – but it's still a shitload of errors.

**Comment by nibirrayy** [comment]
Man @PapyElGringo it still exists. I am using f1a933011a27f5d9c35f85a4f82405db18ae3aa0 commit now
