### ISSUE TITLE
Add option to use theme colors

### ISSUE THREAD

**Issue by Merlin04** [material-shell/material-shell#50]
With a version from yesterday, the menu button was a dark blue color that matched my GTK theme. With the latest version, it has changed to a purple color. Can this be added as an option so the panel can match the theme that I use?
![Old](https://user-images.githubusercontent.com/11800751/60842368-d86a9a80-a188-11e9-9462-14ab2976e5b4.png)
![New](https://user-images.githubusercontent.com/11800751/60842380-dc96b800-a188-11e9-888a-a53da7d41a0f.png)

**Comment by PapyElGringo** [comment]
Yeah I had to disabled this feature until it's done right. It's was buggy.

**Comment by nununoisy** [comment]
What part of the code handles the theme color?

**Comment by PapyElGringo** [comment]
currently the color is defined [here](https://github.com/PapyElGringo/material-shell/blob/b85b30c411f8f2ac7c6963d0cc9b3262e672a3e4/stylesheet.scss#L1)

**Comment by nununoisy** [comment]
How did you previously get the color from GNOME?

**Comment by PapyElGringo** [comment]
[Here](https://github.com/PapyElGringo/material-shell/commit/1f42f3d6d943d41c88c9f711fc021af94108f696#diff-e8fcce0ca92162fb15eb753aec2ac214L36) But like I said was the wrong way to do it

**Comment by erickvieira** [comment]
Can I use environment variables to change the theme color? Like [pywal's rofi specifications](https://github.com/dylanaraps/pywal/wiki/Customization#rofi) for example. Is it possible or will be some day?

**Comment by PapyElGringo** [comment]
It's will be possible to choose the primary color of the interface but maybe not from an environment variable but we will provide this settings

**Comment by PapyElGringo** [comment]
The theme feature should fix this

**Comment by chaosmonk1** [comment]
No, still not fixed.  There are three theme options: Light, Dark, and Primary, which provide hard-coded themes that do not match the user's GTK theme.  There should be a "Native" option or something similar that uses the user's GTK theme.

**Comment by chaosmonk1** [comment]
Or perhaps simpler, just use the user's GTK theme (or shell theme, if that's easier) by default. There is no need to implement a new theming engine when GNOME already has one.

**Comment by sumutcan** [comment]
I am also having an issue with this. One alternative is that you can use a color picker like pop-shell does for the active window frame color.
