### ISSUE TITLE
Instantly crashes after install

### ISSUE THREAD

**Issue by DanielS98** [material-shell/material-shell#797]
**Describe the bug**
Since Debian (sid) upgraded gnome from 3.38+3 to 40 the shell crashes instantly. Even now after I reinstalled Debian at gnome version 42+3 right after I enable material shell it instantly crashes.

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [x] Wayland
- GNOME Shell version: 42+3
- Distro: Debian sid
- Steps to reproduce, if applicable:
Either install via extensions.gnome.org or source. Tried reseting material shell settings too, but didn't change a thing. (There are no other extensions installed)

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```
May 08 16:44:11 debian gnome-shell[309820]: Some code accessed the property 'ENABLED_EXTENSIONS_KEY' on the module 'extensionSystem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
May 08 16:44:11 debian gnome-shell[309820]: --------------
May 08 16:44:11 debian gnome-shell[309820]: INIT EXTENSION
May 08 16:44:11 debian gnome-shell[309820]: --------------
May 08 16:44:11 debian gnome-shell[309820]: ----------------
May 08 16:44:11 debian gnome-shell[309820]: ENABLE EXTENSION
May 08 16:44:11 debian gnome-shell[309820]: ----------------
May 08 16:44:11 debian gnome-shell[309820]: Window manager warning: "<Super>Bottom" found in configuration database is not a valid value for keybinding "move-window-bottom"
May 08 16:44:12 debian gnome-shell[313035]: Running GNOME Shell (using mutter 42.0) as a X11 window and compositing manager
May 08 16:44:12 debian gnome-shell[313035]: ATK Bridge is disabled but a11y has already been enabled.
May 08 16:44:12 debian gnome-shell[313035]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
May 08 16:44:12 debian gnome-shell[313035]: Will monitor session 149
May 08 16:44:12 debian gnome-shell[313035]: Telepathy is not available, chat integration will be disabled.
May 08 16:44:12 debian gnome-shell[313035]: WARNING: addSignalMethods is replacing existing [object Object] connect method
May 08 16:44:12 debian gnome-shell[313035]: WARNING: addSignalMethods is replacing existing [object Object] disconnect method
May 08 16:44:12 debian gnome-shell[313035]: WARNING: addSignalMethods is replacing existing [object Object] emit method
May 08 16:44:12 debian gnome-shell[313035]: Some code accessed the property 'ENABLED_EXTENSIONS_KEY' on the module 'extensionSystem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
May 08 16:44:12 debian gnome-shell[313035]: --------------
May 08 16:44:12 debian gnome-shell[313035]: INIT EXTENSION
May 08 16:44:12 debian gnome-shell[313035]: --------------
May 08 16:44:12 debian gnome-shell[313035]: ----------------
May 08 16:44:12 debian gnome-shell[313035]: ENABLE EXTENSION
May 08 16:44:12 debian gnome-shell[313035]: ----------------
May 08 16:44:12 debian gnome-shell[313035]: show splashscreen
May 08 16:44:12 debian gnome-shell[313035]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
May 08 16:44:12 debian gnome-shell[313035]: Window manager warning: "<Super>Bottom" found in configuration database is not a valid value for keybinding "move-window-bottom"
May 08 16:44:13 debian gnome-shell[313161]: Running GNOME Shell (using mutter 42.0) as a X11 window and compositing manager
May 08 16:44:13 debian gnome-shell[313161]: ATK Bridge is disabled but a11y has already been enabled.
May 08 16:44:13 debian gnome-shell[313161]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
May 08 16:44:13 debian gnome-shell[313161]: Will monitor session 149
May 08 16:44:13 debian gnome-shell[313161]: Telepathy is not available, chat integration will be disabled.
May 08 16:44:13 debian gnome-shell[313161]: Failed to create file /run/user/1000/gnome-shell-disable-extensions: Error opening file “/run/user/1000/gnome-shell-disable-extensions”: File exists
May 08 16:44:13 debian gnome-shell[313161]: WARNING: addSignalMethods is replacing existing [object Object] connect method
May 08 16:44:13 debian gnome-shell[313161]: WARNING: addSignalMethods is replacing existing [object Object] disconnect method
May 08 16:44:13 debian gnome-shell[313161]: WARNING: addSignalMethods is replacing existing [object Object] emit method
May 08 16:44:13 debian gnome-shell[313161]: Some code accessed the property 'ENABLED_EXTENSIONS_KEY' on the module 'extensionSystem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
May 08 16:44:13 debian gnome-shell[313161]: --------------
May 08 16:44:13 debian gnome-shell[313161]: INIT EXTENSION
May 08 16:44:13 debian gnome-shell[313161]: --------------
May 08 16:44:13 debian gnome-shell[313161]: ----------------
May 08 16:44:13 debian gnome-shell[313161]: ENABLE EXTENSION
May 08 16:44:13 debian gnome-shell[313161]: ----------------
May 08 16:44:13 debian gnome-shell[313161]: show splashscreen
May 08 16:44:13 debian gnome-shell[313161]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
May 08 16:44:13 debian gnome-shell[313161]: Window manager warning: "<Super>Bottom" found in configuration database is not a valid value for keybinding "move-window-bottom"
May 08 16:44:13 debian gnome-shell[313264]: Running GNOME Shell (using mutter 42.0) as a X11 window and compositing manager
May 08 16:44:14 debian gnome-shell[313264]: ATK Bridge is disabled but a11y has already been enabled.
May 08 16:44:14 debian gnome-shell[313264]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
May 08 16:44:14 debian gnome-shell[313264]: Will monitor session 149
May 08 16:44:14 debian gnome-shell[313264]: Telepathy is not available, chat integration will be disabled.
May 08 16:44:14 debian gnome-shell[313264]: Failed to create file /run/user/1000/gnome-shell-disable-extensions: Error opening file “/run/user/1000/gnome-shell-disable-extensions”: File exists
May 08 16:44:14 debian gnome-shell[313264]: WARNING: addSignalMethods is replacing existing [object Object] connect method
May 08 16:44:14 debian gnome-shell[313264]: WARNING: addSignalMethods is replacing existing [object Object] disconnect method
May 08 16:44:14 debian gnome-shell[313264]: WARNING: addSignalMethods is replacing existing [object Object] emit method
May 08 16:44:14 debian gnome-shell[313264]: Some code accessed the property 'ENABLED_EXTENSIONS_KEY' on the module 'extensionSystem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
May 08 16:44:14 debian gnome-shell[313264]: --------------
May 08 16:44:14 debian gnome-shell[313264]: INIT EXTENSION
May 08 16:44:14 debian gnome-shell[313264]: --------------
May 08 16:44:14 debian gnome-shell[313264]: ----------------
May 08 16:44:14 debian gnome-shell[313264]: ENABLE EXTENSION
May 08 16:44:14 debian gnome-shell[313264]: ----------------
May 08 16:44:14 debian gnome-shell[313264]: show splashscreen
May 08 16:44:14 debian gnome-shell[313264]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
May 08 16:44:14 debian gnome-shell[313264]: Window manager warning: "<Super>Bottom" found in configuration database is not a valid value for keybinding "move-window-bottom"
May 08 16:49:44 debian gnome-shell[314360]: Running GNOME Shell (using mutter 42.0) as a X11 window and compositing manager
May 08 16:49:44 debian gnome-shell[314360]: ATK Bridge is disabled but a11y has already been enabled.
May 08 16:49:44 debian gnome-shell[314360]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
May 08 16:49:44 debian gnome-shell[314360]: Will monitor session 152
May 08 16:49:44 debian gnome-shell[314360]: Telepathy is not available, chat integration will be disabled.
May 08 16:49:44 debian gnome-shell[314360]: Failed to create file /run/user/1000/gnome-shell-disable-extensions: Error opening file “/run/user/1000/gnome-shell-disable-extensions”: File exists
May 08 16:49:44 debian gnome-shell[314360]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
May 08 16:49:46 debian gnome-shell[314360]: GNOME Shell started at Sun May 08 2022 16:49:44 GMT-0300 (Brasilia Standard Time)
May 08 16:49:46 debian gnome-shell[314360]: Registering session with GDM
May 08 16:49:53 debian gnome-shell[314360]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x280000c
May 08 16:49:53 debian gnome-shell[314360]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x280000c
May 08 16:50:43 debian gnome-shell[314360]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x280000c
```

**Comment by billyjbryant** [comment]
I have a very similar situation. 

* Occurs on:
  * [x] X.Org
  * [x] Wayland
* GNOME Shell version: 3.36.9
* Distro: Ubuntu 20.04.4 LTS (Focal Fossa)
* Steps to reproduce, if applicable: Install extension via extensions.gnome.org and enable in Gnome Extensions Settings with multiple monitors. Single monitor (Laptop Display) works with no issue, as soon as a 2nd monitor is introduced via a Dock or the laptop HDMI port, material-shell crashes. 


### Log data
Output from journalctl /usr/bin/gnome-shell:
```
Jun 08 11:27:01 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: --------------
Jun 08 11:27:01 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: INIT EXTENSION
Jun 08 11:27:01 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: --------------
Jun 08 11:27:01 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: ----------------
Jun 08 11:27:01 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: ENABLE EXTENSION
Jun 08 11:27:01 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: ----------------
Jun 08 11:27:01 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: JS WARNING: [/home/billy/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/module/disableIncompatibleExtensionsModule.js 37]: referenc>
Jun 08 11:27:01 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: disable error, desktop-icons@csoriano, TypeError: extension.stateObj is undefined
Jun 08 11:27:01 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: JS WARNING: [/home/billy/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/msFocusManager.js 15]: reference to undefined prope>
Jun 08 11:27:01 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: JS WARNING: [/home/billy/.local/share/gnome-shell/extensions/material-shell@papyelgringo/extension.js 79]: reference to undefined property "workspaces-s>
Jun 08 11:27:01 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: Window manager warning: "<Super>Bottom" found in configuration database is not a valid value for keybinding "move-window-bottom"
Jun 08 11:27:02 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: JS WARNING: [/home/billy/.local/share/gnome-shell/extensions/material-shell@papyelgringo/src/manager/stateManager.js 90]: reference to undefined propert>
Jun 08 11:27:02 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: ----------------
Jun 08 11:27:02 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: EXTENSION LOADED
Jun 08 11:27:02 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: ----------------
Jun 08 11:27:02 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: --------------------
Jun 08 11:27:02 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: END EXTENSION LOADED
Jun 08 11:27:02 uc0d9731d58c75a.ant.amazon.com gnome-shell[12460]: --------------------
```

**Comment by PapyElGringo** [comment]
We are only compatible to gnome 40+

Le mer. 8 juin 2022, 22:40, Billy Bryant ***@***.***> a
écrit :

**Comment by HalfVoxel** [comment]
Tons of crashes have been fixed recently. Would you mind trying again?

**Comment by baf57** [comment]
I can confirm that on Debian Sid this is still an issue on both Wayland and Xorg. I had a brief discussion with @PapyElGringo about this on Discord, but there didn't seem to be too much in the way of explicitly useful information in the logs or what I was able to do at their request. I am attaching here both the logs I sent there in case someone can get any more useful information out of these than I can.

Wayland:
```
Aug 12 17:16:12 debian gnome-shell[10084]: Using public X11 display :0, (using :1 for managed services)
Aug 12 17:16:12 debian gnome-shell[10084]: Using Wayland display name 'wayland-0'
Aug 12 17:16:12 debian gnome-shell[10084]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Aug 12 17:16:12 debian gnome-shell[10084]: Will monitor session 17
Aug 12 17:16:12 debian gnome-shell[10084]: Telepathy is not available, chat integration will be disabled.
Aug 12 17:16:12 debian gnome-shell[10084]: WARNING: addSignalMethods is replacing existing [object Object] connect method
Aug 12 17:16:12 debian gnome-shell[10084]: WARNING: addSignalMethods is replacing existing [object Object] disconnect method
Aug 12 17:16:12 debian gnome-shell[10084]: WARNING: addSignalMethods is replacing existing [object Object] emit method
Aug 12 17:16:12 debian gnome-shell[10084]: Some code accessed the property 'ENABLED_EXTENSIONS_KEY' on the module 'extensionSystem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Aug 12 17:16:12 debian gnome-shell[10084]: --------------
Aug 12 17:16:12 debian gnome-shell[10084]: INIT EXTENSION
Aug 12 17:16:12 debian gnome-shell[10084]: --------------
Aug 12 17:16:12 debian gnome-shell[10084]: ----------------
Aug 12 17:16:12 debian gnome-shell[10084]: ENABLE EXTENSION
Aug 12 17:16:12 debian gnome-shell[10084]: ----------------
Aug 12 17:16:12 debian gnome-shell[10084]: show splashscreen
Aug 12 17:16:12 debian gnome-shell[10084]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
```

Xorg (I did this a while ago so I can't remember which is the failed launch, but it's one of these):
```
Aug 04 12:04:40 debian gnome-shell[47237]: Running GNOME Shell (using mutter 42.3) as a X11 window and compositing manager
Aug 04 12:04:40 debian gnome-shell[47237]: Enabling experimental feature 'scale-monitor-framebuffer'
Aug 04 12:04:40 debian gnome-shell[47237]: Failed to read monitors config file '/home/brayden/.config/monitors.xml': Logical monitor scales must be identical
Aug 04 12:04:40 debian gnome-shell[47237]: ATK Bridge is disabled but a11y has already been enabled.
Aug 04 12:04:40 debian gnome-shell[47237]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Aug 04 12:04:40 debian gnome-shell[47237]: Will monitor session 43
Aug 04 12:04:40 debian gnome-shell[47237]: Telepathy is not available, chat integration will be disabled.
Aug 04 12:04:41 debian gnome-shell[47237]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Aug 04 12:04:43 debian gnome-shell[47237]: GNOME Shell started at Thu Aug 04 2022 12:04:40 GMT-0400 (Eastern Daylight Time)
Aug 04 12:04:43 debian gnome-shell[47237]: Registering session with GDM
Aug 04 12:04:46 debian gnome-shell[47237]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3000004
Aug 04 12:04:46 debian gnome-shell[47237]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3000004
Aug 04 12:04:49 debian gnome-shell[47237]: WARNING: addSignalMethods is replacing existing [object Object] connect method
Aug 04 12:04:49 debian gnome-shell[47237]: WARNING: addSignalMethods is replacing existing [object Object] disconnect method
Aug 04 12:04:49 debian gnome-shell[47237]: WARNING: addSignalMethods is replacing existing [object Object] emit method
Aug 04 12:04:49 debian gnome-shell[47237]: Some code accessed the property 'ENABLED_EXTENSIONS_KEY' on the module 'extensionSystem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Aug 04 12:04:49 debian gnome-shell[47237]: --------------
Aug 04 12:04:49 debian gnome-shell[47237]: INIT EXTENSION
Aug 04 12:04:49 debian gnome-shell[47237]: --------------
Aug 04 12:04:49 debian gnome-shell[47237]: ----------------
Aug 04 12:04:49 debian gnome-shell[47237]: ENABLE EXTENSION
Aug 04 12:04:49 debian gnome-shell[47237]: ----------------
Aug 04 12:04:49 debian gnome-shell[48569]: Running GNOME Shell (using mutter 42.3) as a X11 window and compositing manager
Aug 04 12:04:49 debian gnome-shell[48569]: Enabling experimental feature 'scale-monitor-framebuffer'
Aug 04 12:04:49 debian gnome-shell[48569]: Failed to read monitors config file '/home/brayden/.config/monitors.xml': Logical monitor scales must be identical
Aug 04 12:04:49 debian gnome-shell[48569]: ATK Bridge is disabled but a11y has already been enabled.
Aug 04 12:04:49 debian gnome-shell[48569]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Aug 04 12:04:49 debian gnome-shell[48569]: Will monitor session 43
Aug 04 12:04:49 debian gnome-shell[48569]: Telepathy is not available, chat integration will be disabled.
Aug 04 12:04:50 debian gnome-shell[48569]: Failed to create file /run/user/1000/gnome-shell-disable-extensions: Error opening file “/run/user/1000/gnome-shell-disable-extensions”: File exists
Aug 04 12:04:50 debian gnome-shell[48569]: WARNING: addSignalMethods is replacing existing [object Object] connect method
Aug 04 12:04:50 debian gnome-shell[48569]: WARNING: addSignalMethods is replacing existing [object Object] disconnect method
Aug 04 12:04:50 debian gnome-shell[48569]: WARNING: addSignalMethods is replacing existing [object Object] emit method
Aug 04 12:04:50 debian gnome-shell[48569]: Some code accessed the property 'ENABLED_EXTENSIONS_KEY' on the module 'extensionSystem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Aug 04 12:04:50 debian gnome-shell[48569]: --------------
Aug 04 12:04:50 debian gnome-shell[48569]: INIT EXTENSION
Aug 04 12:04:50 debian gnome-shell[48569]: --------------
Aug 04 12:04:50 debian gnome-shell[48569]: ----------------
Aug 04 12:04:50 debian gnome-shell[48569]: ENABLE EXTENSION
Aug 04 12:04:50 debian gnome-shell[48569]: ----------------
Aug 04 12:04:50 debian gnome-shell[48569]: show splashscreen
Aug 04 12:04:50 debian gnome-shell[48569]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Aug 04 12:04:50 debian gnome-shell[48660]: Running GNOME Shell (using mutter 42.3) as a X11 window and compositing manager
Aug 04 12:04:50 debian gnome-shell[48660]: Enabling experimental feature 'scale-monitor-framebuffer'
Aug 04 12:04:50 debian gnome-shell[48660]: Failed to read monitors config file '/home/brayden/.config/monitors.xml': Logical monitor scales must be identical
Aug 04 12:04:51 debian gnome-shell[48660]: ATK Bridge is disabled but a11y has already been enabled.
Aug 04 12:04:51 debian gnome-shell[48660]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Aug 04 12:04:51 debian gnome-shell[48660]: Will monitor session 43
Aug 04 12:04:51 debian gnome-shell[48660]: Telepathy is not available, chat integration will be disabled.
Aug 04 12:04:51 debian gnome-shell[48660]: Failed to create file /run/user/1000/gnome-shell-disable-extensions: Error opening file “/run/user/1000/gnome-shell-disable-extensions”: File exists
Aug 04 12:04:51 debian gnome-shell[48660]: WARNING: addSignalMethods is replacing existing [object Object] connect method
Aug 04 12:04:51 debian gnome-shell[48660]: WARNING: addSignalMethods is replacing existing [object Object] disconnect method
Aug 04 12:04:51 debian gnome-shell[48660]: WARNING: addSignalMethods is replacing existing [object Object] emit method
Aug 04 12:04:51 debian gnome-shell[48660]: Some code accessed the property 'ENABLED_EXTENSIONS_KEY' on the module 'extensionSystem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Aug 04 12:04:51 debian gnome-shell[48660]: --------------
Aug 04 12:04:51 debian gnome-shell[48660]: INIT EXTENSION
Aug 04 12:04:51 debian gnome-shell[48660]: --------------
Aug 04 12:04:51 debian gnome-shell[48660]: ----------------
Aug 04 12:04:51 debian gnome-shell[48660]: ENABLE EXTENSION
Aug 04 12:04:51 debian gnome-shell[48660]: ----------------
Aug 04 12:04:51 debian gnome-shell[48660]: show splashscreen
Aug 04 12:04:51 debian gnome-shell[48660]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Aug 04 12:05:00 debian gnome-shell[49443]: Running GNOME Shell (using mutter 42.3) as a X11 window and compositing manager
Aug 04 12:05:00 debian gnome-shell[49443]: Enabling experimental feature 'scale-monitor-framebuffer'
Aug 04 12:05:00 debian gnome-shell[49443]: Failed to read monitors config file '/home/brayden/.config/monitors.xml': Logical monitor scales must be identical
Aug 04 12:05:00 debian gnome-shell[49443]: ATK Bridge is disabled but a11y has already been enabled.
Aug 04 12:05:00 debian gnome-shell[49443]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Aug 04 12:05:00 debian gnome-shell[49443]: Will monitor session 46
Aug 04 12:05:01 debian gnome-shell[49443]: Telepathy is not available, chat integration will be disabled.
Aug 04 12:05:01 debian gnome-shell[49443]: Failed to create file /run/user/1000/gnome-shell-disable-extensions: Error opening file “/run/user/1000/gnome-shell-disable-extensions”: File exists
Aug 04 12:05:02 debian gnome-shell[49443]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Aug 04 12:05:03 debian gnome-shell[49443]: GNOME Shell started at Thu Aug 04 2022 12:05:01 GMT-0400 (Eastern Daylight Time)
Aug 04 12:05:03 debian gnome-shell[49443]: Registering session with GDM
```

**Comment by IceDBorn** [comment]
I can confirm this is happening in NixOS too.
